version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    image: ${APPNAME}:${IMAGENAME}
    container_name: ${CONTAINERNAMEDJ}
    command: python manage.py runserver 0.0.0.0:${HOST_PORT}
    depends_on:
      - ${DB_HOST}
  db:
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    container_name: ${CONTAINERNAMEDB}
    command: -p ${DB_PORT}
