version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    env_file:
      - ./.env
    image: ${APPNAME}:${IMAGENAME}
    container_name: ${CONTAINERNAMEDJ}
    command: python manage.py runserver 0.0.0.0:${HOST_PORT}
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    container_name: ${CONTAINERNAMEDB}
    command: -p ${SQL_PORT}