version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    image: app:${IMAGENAME}
    container_name: ${CONTAINERNAMEDJ}
    command: python manage.py runserver 0.0.0.0:${HOST_PORT}
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: ${CONTAINERNAMEDB}
    command: -p ${DB_PORT}