# Generated by Django 3.2.7 on 2021-11-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('request_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('pipeline_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('system_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='', max_length=30)),
                ('system_active', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_type', models.IntegerField(choices=[(1, 'Adduser'), (2, 'Deleteuser'), (3, 'Modifyuser'), (4, 'Resetpassword')])),
                ('script_string', models.TextField()),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cslabman.systems')),
            ],
            options={
                'verbose_name_plural': 'Scripts',
            },
        ),
        migrations.CreateModel(
            name='AccountRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(default='', max_length=150)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.IntegerField(choices=[(1, 'Incomplete'), (2, 'Hold'), (3, 'Noscript'), (4, 'Complete')], default=1)),
                ('request_complete', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('pipeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cslabman.students')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cslabman.requesttype')),
                ('system_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cslabman.systems')),
            ],
            options={
                'verbose_name_plural': 'Account Requests',
            },
        ),
    ]
