# Generated by Django 3.2.7 on 2021-10-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('mnumber', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('system_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('script_id', models.AutoField(primary_key=True, serialize=False)),
                ('script_type', models.IntegerField(choices=[(1, 'Adduser'), (2, 'Deleteuser'), (3, 'Modifyuser')])),
                ('script_string', models.TextField()),
                ('system_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cslabman.systems')),
            ],
        ),
        migrations.CreateModel(
            name='AccountRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.IntegerField(choices=[(1, 'Adduser'), (2, 'Deleteuser'), (3, 'Modifyuser')])),
                ('request_datetime', models.DateTimeField()),
                ('request_status', models.IntegerField(choices=[(1, 'Incomplete'), (2, 'Hold'), (3, 'Noscript'), (4, 'Complete')])),
                ('request_complete', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('mnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cslabman.students')),
                ('system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cslabman.systems')),
            ],
        ),
    ]
