# Generated by Django 3.2.7 on 2021-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cslabman', '0002_alter_scripts_system_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequests',
            options={'verbose_name_plural': 'Account Requests'},
        ),
        migrations.AlterModelOptions(
            name='scripts',
            options={'verbose_name_plural': 'Scripts'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='systems',
            options={'verbose_name_plural': 'Systems'},
        ),
        migrations.RenameField(
            model_name='accountrequests',
            old_name='system_id',
            new_name='system_name',
        ),
        migrations.RenameField(
            model_name='scripts',
            old_name='system_id',
            new_name='system_name',
        ),
        migrations.RemoveField(
            model_name='systems',
            name='system_id',
        ),
        migrations.AddField(
            model_name='accountrequests',
            name='reason',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='accountrequests',
            name='request_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountrequests',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'Adduser'), (2, 'Deleteuser'), (3, 'Modifyuser'), (4, 'Resetpassword')]),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='script_type',
            field=models.IntegerField(choices=[(1, 'Adduser'), (2, 'Deleteuser'), (3, 'Modifyuser'), (4, 'Resetpassword')]),
        ),
        migrations.AlterField(
            model_name='systems',
            name='system_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
